spring:
  datasource:
    username: bharath
    url: jdbc:mysql://localhost:3306/db_student?allowPublicKeyRetrieval=true&useSSL=false
    password: ********
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: DEPARTMENT-SERVICE
    
server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true